### ISSUE TITLE
No glyxtoolMS nodes in opmass

### ISSUE THREAD

**Issue by glycohezhu** [glyXera/glyXtoolMS#2]
Hi
After I did the configuration of glyxtoolms and save it, there are no glyxtoolms nodes in the external part. Please check the following link for details. The OS is win 7. 
https://ibb.co/gcFosK
https://ibb.co/bzO2Kz

Best,
He

**Comment by mpioch** [comment]
Thank you - the underlying packaging error is now fixed. Depending on the python package installer the TOPP scripts were copied to a wrong destination.

With Best Regards,
Markus Pioch
